name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Backend Image
      run: |
        docker build -t backend ./Application-Code/backend
        docker tag backend:latest ${{ steps.login-ecr.outputs.registry }}/three-tier-backend:latest

    - name: Push Backend Image
      run: |
        docker push ${{ steps.login-ecr.outputs.registry }}/three-tier-backend:latest

    - name: Build Frontend Image
      run: |
        docker build -t frontend ./Application-Code/frontend
        docker tag frontend:latest ${{ steps.login-ecr.outputs.registry }}/three-tier-frontend:latest

    - name: Push Frontend Image
      run: |
        docker push ${{ steps.login-ecr.outputs.registry }}/three-tier-frontend:latest
